apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  annotations:
    appstudio.openshift.io/application: test-app-167111763
    appstudio.openshift.io/component: java-quarkus
    build.appstudio.openshift.io/build: "true"
    build.appstudio.openshift.io/type: build
    build.appstudio.openshift.io/version: "0.1"
    pipelines.appstudio.openshift.io/type: build
  creationTimestamp: null
  name: java-quarkus
  namespace: karthik
spec:
  namespaceSelector: {}
  resources: {}
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - kind: ClusterTriggerBinding
      ref: github-push
    template:
      ref: java-quarkus
status:
  configuration:
    generatedName: ""
